---
- name: Install EPEL RELEASE
  hosts: localhost
  tasks:
    - name: Installing epel-release
      yum:
        name: epel-release
        state: latest

    - name: Install Nginx
      yum: 
        name: nginx
        state: latest
      
    - name: Start and Enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes
