---
- name: Update all packages, Install packages, Create and insert lines to a file
  hosts: host1
  tasks:
    - name: Updating all packages
      yum: 
        name: '*'
        state: latest
        exclude: kernel*,foo*    

    - name: Adding Epel repo
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgcheck: no
        state: present 

    - name: Installing Nginx
      yum:
        name: nginx
        state: present    

    - name: Starting Nginx
      service:
        name: nginx
        state: started
        enabled: yes    


 

          


#    - name: Installing packages
#      yum:
#        name: httpd
#        state: latest

#    - name: Create a empty file
#      file: 
#        path: /tmp/ansible_file
#        state: touch 
#
#    - name: Write into file
#      blockinfile:
#        path: /tmp/ansible_file
#        block: | 
#          This is line one
#          This is line two
   
   
#  - command: yum update -y
        
