---
- name: Update all packages
  hosts: localhost
  tasks:
    - name: Updating packages
      yum: 
        name: '*'
        state: latest
         
   
   
   
  #  - command: yum update -y
        
