---
- name: Update all packages, Install packages, Create and insert lines to a file
  hosts: multi
  tasks:
    - name: Updating all packages
      yum: 
        name: '*'
        state: latest
        exclude: kernel*,foo*     

    - name: Installing packages
      yum:
        name: ["vim","tree","wget","curl"]
        state: latest

    - name: Create a empty file
      file: 
        path: /tmp/ansible_file
        state: touch 

    - name: Write into file
      blockinfile:
        path: /tmp/ansible_file
        block: | 
          This is line one
          This is line two
   
   
  #  - command: yum update -y
        
