---
- name: Update all packages
  hosts: multi
  tasks:
    - name: Updating packages
      yum: 
        name: '*'
        state: latest
        exclude: kernel*,foo*         
   
   
   
  #  - command: yum update -y
        
